[advisories]
version = 2
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
ignore = [
    #"RUSTSEC-0000-0000",
]

[licenses]
version = 2
allow = [
    "MIT",
    "BSD-3-Clause",
    "Apache-2.0",
    "Unicode-3.0",
]

[bans]
skip = [
    #{ name = "ansi_term", version = "=0.11.0" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[output]
feature-depth = 1
