[package]
name = "spacebadgers"
version = "1.1.0"
edition = "2021"
description = "Fast SVG badge generator"

license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
htmlize = "1.0.2"
indoc = "2.0.1"

[dev-dependencies]
insta = "1.29.0"
