name: spacebadgers

on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10
  RUST_BACKTRACE: short
  RUSTDOCFLAGS: -Dwarnings

jobs:
  test:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: rustup toolchain install stable --profile default
      - name: cargo test
        run: cargo test --release -p spacebadgers
      - name: cargo test (doctests)
        run: cargo test --release --doc -p spacebadgers
      - name: cargo clippy
        run: cargo clippy -p spacebadgers
      - name: rustfmt
        run: cargo fmt -p spacebadgers --check
