name: worker

on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10
  RUST_BACKTRACE: short
  RUSTDOCFLAGS: -Dwarnings

jobs:
  test:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: rustup toolchain install stable --profile default
      - name: cargo test
        run: cargo test --release -p badgers-worker
      - name: cargo test (doctests)
        run: cargo test --release --doc -p badgers-worker
      - name: cargo clippy
        run: cargo clippy -p badgers-worker
      - name: rustfmt
        run: cargo fmt -p badgers-worker --check
  deploy:
    needs: [test]
    if: github.ref == 'refs/heads/main'
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: rustup toolchain install stable --profile minimal
      - name: Enable corepack
        run: corepack enable
      - name: Use Node 21
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: yarn
      - run: yarn install --immutable
        working-directory: ./badgers-worker
      - name: Deploy to Cloudflare
        run: npx wrangler deploy
        working-directory: ./badgers-worker
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
